spring:
  profiles:
    active: "local"
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:9020
          predicates:
            - Path=/users/**
        - id: notification
          uri: http://localhost:8090
          predicates:
            - Path=/notifications/**
        - id: default-route
          uri: http://localhost:8085
          predicates:
            - Path=/**
server:
  port: 8080
